/* CART */
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
/* WISHLIST */
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const WISHLIST_TO_CART= 'WISHLIST_TO_CART'
export const REMOVE_TO_WISHLIST = 'REMOVE_TO_WISHLIST'
export const EMPTY_WISHLIST = 'EMPTY_WISHLIST'
/* PRODUCT GET */
export const PRODUCT_SET = 'PRODUCT_SET'






